name: run_scraper

on:
  schedule:
    - cron: '07 11 * * *'

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  run_thingy:
    runs-on: ubuntu-latest
     env:
          RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      # install renv package
      - run: R -e 'install.packages("renv")'
      # set up cache
      - name: Cache packages
        uses: actions/cache@v1
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
           restore-keys: |-
              ${{ runner.os }}-renv-
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      # install c++ dependencies and install necessary packages
      - run: R -e 'renv::restore()'
      # execute Rscript
      - run: Rscript scraper.R
